Repository googleapis/nodejs-language, pull requests merged in 2019-05, with the labels that each got.

#231 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#232 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#233 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#236 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#237 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#238 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#235 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, status: blocked

#239 fix: DEADLINE_EXCEEDED error is no longer retried
  src/v1/language_service_client_config.json
  src/v1beta2/language_service_client_config.json
  synth.metadata
Labels: cla: yes

#241 fix: DEADLINE_EXCEEDED is idempotent
  src/v1/language_service_client_config.json
  src/v1beta2/language_service_client_config.json
  synth.metadata
Labels: cla: yes

#244 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#248 chore: release 3.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#249 refactor: drop dependency on lodash.merge and update links
  src/v1/language_service_client.js
  src/v1beta2/language_service_client.js
  synth.metadata
Labels: cla: yes

#250 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#251 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#252 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#253 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
