Repository googleapis/nodejs-language, pull requests merged in 2020-07, with the labels that each got.

#479 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#481 typeo
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#483 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#484 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#485 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#488 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#489 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#490 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#491 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#492 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#493 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#494 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
