Repository googleapis/nodejs-language, pull requests merged in 2020-06, with the labels that each got.

#468 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#471 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/language_service_client.ts
  src/v1beta2/language_service_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#474 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#475 fix: ensure gax is usable from electron
  src/v1/language_service_client.ts
  src/v1beta2/language_service_client.ts
  synth.metadata
Labels: cla: yes, context: none

#476 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#477 build: use bazel for library generation
  synth.metadata
  synth.py
Labels: cla: yes

#478 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
