Repository googleapis/nodejs-language, pull requests merged in 2020-05, with the labels that each got.

#458 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes

#461 fix: regenerate unit tests
  synth.metadata
  test/gapic_language_service_v1.ts
  test/gapic_language_service_v1beta2.ts
Labels: automerge, cla: yes

#463 fix: synth.py clean up for multiple version
  samples/automl/automlNaturalLanguageDataset.js
  samples/automl/automlNaturalLanguageModel.js
  samples/automl/automlNaturalLanguagePredict.js
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#465 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#459 automl: delete unused samples
  samples/automl/automlNaturalLanguageDataset.js
  samples/automl/automlNaturalLanguageModel.js
  samples/automl/automlNaturalLanguagePredict.js
  samples/automl/resources/test.txt
  samples/automlNaturalLanguageDataset.js
  samples/automlNaturalLanguageModel.js
  samples/automlNaturalLanguagePredict.js
Labels: automerge, cla: yes

#467 docs: remove retired samples from README
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none
